### ISSUE TITLE
Other psifidos applets and projects

### ISSUE THREAD

**Issue by michaldybczak** [dhruv8sh/plasma6-window-title-applet#11]
Do you have any plans porting other applets like appmenu and buttons from psifidos? I guess that latte is out of question ;) ?

**Comment by dhruv8sh** [comment]
Fortunately, this was already done by other people. See [this](https://github.com/moodyhunter/applet-window-buttons6).
This is also already available on the AUR. Hence there is no need for me to do duplicate work.

**Comment by D3SOX** [comment]
Small correction: The one you linked is actually [in the official Arch repos](https://archlinux.org/packages/extra/x86_64/plasma-applet-window-buttons/)

**Comment by michaldybczak** [comment]
OK, so we have buttons, titles, appmenu, but we are still missing two big features:

- stripping of titlebar when window is maximized
- dynamic panel transparency (transparent panel when window is not maximized and no window is touching it, and solid panel when window is maximized or a window is touching it).

Of course, there are other, smaller features that are missing, but those above are really important to have a somewhat functional upper panel with global menus, because with titlebars doing nothing and taking up space, the whole setup is pointless. While having solid or visible panel also is disturbing. I loved how we could set on latte the panel to be fully transparent or partially transparent, as much as we needed to. Of course, dynamic colors based on the wallpaper was an extra feature that probably I can't hope right now.

I hope that with time, some of the features will be back in one form or another.

**Comment by dhruv8sh** [comment]
Please elaborate on the stripping of titlebar functionality.
Also, you can set the transparency of the panel using the following:
- Panel colorizer
- Transparency toggle
- AlphaBlack Plasma Style with AlphaBlack control applet ( I use this )

**Comment by michaldybczak** [comment]
Latte had a setting that, when enabled, any maximized window became without titlebar. This was awesome, because titlebar in maximized state is useless if you have buttons, title, appmenu and systray in the upper panel.

Currently, without that feature, titlebar is just duplicating buttons and title or looking at it differently, there would be no need for buttons or tile applet on the upper panel with titlebar.

Look at my very, very old video where you can see that when I maximize any app, it doesn't have titlebar and its elements are shown on the upper panel:

https://www.youtube.com/watch?v=gcMS1GfkiWk

This was a bit hidden option in latte, but it was there from the very beginning. In a way, kwin or some kwin scrips also allow for this kind of behavior, but they weren't working as well.

This is still possible, because without latte, the config was still working but incorrectly, stripping titlebar from windows in any state, so also from unmaximized ones. I had to clean my configs after transferring to Plasma 6 to fix various issues and this lack of titlabar.

**Comment by dhruv8sh** [comment]
Oh of course!
You are referring to the Unity-like behavior. This has been in KDE for forever, latte simple provided a toggle for this.
Check [this](https://discuss.kde.org/t/hide-titlebars-of-maximised-windows/1162) out.

**Comment by D3SOX** [comment]
> stripping of titlebar when window is maximized

@michaldybczak Do you mean that titlebars are gone when the window is maximzed? That did not change.
It was sucessfully migrated when I upgraded to Plasma 6.
You probably just have to enable it
```bash
kwriteconfig6 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true
qdbus org.kde.KWin /KWin reconfigure
```
