### ISSUE TITLE
[Feature request] Show window information from screen separately

### ISSUE THREAD

**Issue by D3SOX** [dhruv8sh/plasma6-window-title-applet#14]
Similar to https://github.com/moodyhunter/applet-window-buttons6/issues/4

It would be great it this applet could also support displaying it separately when using multiple screens
Meaning with this setting it would show the name of the last active window for that screen

**Comment by dhruv8sh** [comment]
Unfortunately, KDE Framework don't provide a way to do this currently. Remembering the name CAN break things introducing buggy behavior.
See #6. Closing as a duplicate.

**Comment by D3SOX** [comment]
Hm okay, I would be more than happy with a little buggy behavior than not having this at all
I've seen the other issue but thought this is not a duplicate as there was a different conversation and I haven't read it to the end
