### ISSUE TITLE
option to choose some text instead of "default"

### ISSUE THREAD

**Issue by zayronxio** [dhruv8sh/plasma6-window-title-applet#15]
Please add some option to choose some text instead of "default"

**Comment by dhruv8sh** [comment]
This already exists.
Go to Behavior settings, disable 'Show activity information' and enter the custom text in the Text field under it.

**Comment by Gpinchon** [comment]
Somehow "Show activity information" is missing from the options

**Comment by dhruv8sh** [comment]
@Gpinchon this solution is from a previous version.
There was a recent overhaul to change everything
