### ISSUE TITLE
Inkscape does not use the global menu.

### ISSUE THREAD

**Issue by alohaia** [dhruv8sh/plasma6-window-title-applet#17]
Inkscape does not use the global menu, and its own menu disappears.

![image](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/36324537/ea6a8df7-9f8a-4f12-aa0b-babaf635e6bb)

**Comment by dhruv8sh** [comment]
This unfortunately would not be right place to ask for this. I am not maintaining Global menu applet, or Inkscape.
Have you tried asking on [r/kde](https://www.reddit.com/r/kde/)?

Hint: It's a problem with appimages. [Look at this](https://www.reddit.com/r/Inkscape/comments/svuee2/menu_bar_is_gone_and_i_cant_get_it_back_have/).
