### ISSUE TITLE
kf.package: Invalid metadata for package structure "Plasma/Applet"

### ISSUE THREAD

**Issue by ameris1** [dhruv8sh/plasma6-window-title-applet#18]
Trying to install it via terminal and this is the output I'm getting

```
kpackagetool5 -i  ./
kf.package: Invalid metadata for package structure "Plasma/Applet"
Package type "Plasma/Applet" not found
Successfully installed /home/notsure/Downloads/plasma6-window-title-applet-0.4

```
Doesn't show up in my widget list after. Pretty sure this is dependency issue on my side. Dunno where else to post this.

**Comment by dhruv8sh** [comment]
Because this is a package for plasma 6.
Either use kpackagetool6 or plasmapkg2.
kpackagetool5 is for Plasma 5.

**Comment by ameris1** [comment]
I'm using Plasma 6 and am following the instructions as you posted

![Screenshot_20240407_130432](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/120804279/cae64287-23da-42d9-ac5f-f391caed0931)

I'm using KDE Neon which version is 

![Screenshot_20240407_130630](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/120804279/cda5c172-9958-4330-b8bc-37eeb2c7c1f6)


When I try kpackagetool6 -i  ./:

`qt.dbus.integration: QDBusConnection: error: could not send signal to service "" path "/KPackage/" interface "org.kde.plasma.kpackage" member "packageInstalled": Invalid object path: /KPackage/
Successfully installed /home/notsure/.local/share/kpackage/generic/org.kde.windowtitle/
`

**Comment by dhruv8sh** [comment]
Yes this should've installed the applet. Was it not installed? There has been a bug in kpackagetool6 as well.
plasmapkg2 works every time though, so it should work just fine. Use ```plasmapkg2 -i .```.


Thanks for pointing out that it was left without modifications. I am quite shocked it went unnoticed up until now.

**Comment by ameris1** [comment]
lol now I'm getting an error I shouldn't be getting on KDE Neon's side

Command 'plasmapkg2' not found, but can be installed with:
sudo apt install plasma-framework

Needless to say I have plasma-framework (as it is standard for KDE Plasma).

Now I have another bug to report...

**Comment by dhruv8sh** [comment]
You can manually install the applet by placing the cloned folder into ```~/.local/share/plasma/plasmoids/``` and renaming it to ```org.kde.windowtitle```.
Then run ```systemctl --user restart plasma-plasmashell``` to restart the shell and it should show up.

**Comment by ameris1** [comment]
That worked. Thank you!

**Comment by BlueDrink9** [comment]
I had issues too, but ` kpackagetool6 --type Plasma/Applet --install "$dir"` seems to have worked for me - just need to specify that this is an applet.
@dhruv8sh I would encourage you to add this to the readme, especially with plasmapkg2 not in many kde6 installs.
