### ISSUE TITLE
Installation on KDE neon with Plasma 6 is broken

### ISSUE THREAD

**Issue by briskycat** [dhruv8sh/plasma6-window-title-applet#19]
Latest KDE neon with Plasma 6.0.3. After cloning this repository and running `kpackagetool6 -i ./ ` as described in `README.md` the applet doesn't get added to the list of applets. Running `kpackagetool6 --list` gives the following output:
```
Listing KPackageType: KPackage/Generic in /home/andy/.local/share/kpackage/generic/
KPackageStructure of KPluginMetaData(pluginId:"org.kde.windowtitle", fileName: "/home/andy/.local/share/kpackage/generic/org.kde.windowtitle/metadata.json") does not match requested format "KPackage/Generic"
```

**Comment by dhruv8sh** [comment]
Recently #18 had the same issue.
kpackagetool6 is currently broken and places widgets in a folder which plasma does not even checks for widgets.
Use ```plasmapkg2 -i .``` to install instead. Or you can manually install through steps given in #18.

**Comment by briskycat** [comment]
@dhruv8sh `plasmapkg2` is not available in KDE Neon. See https://bugs.kde.org/show_bug.cgi?id=485195. It used to be in `plasma-framework`, but, as Nate mentioned, it is no longer there. It is not in `libplasma6`/`libplasma-dev` either.
Thus, KDE Neon support is currently non-functional.
