### ISSUE TITLE
Add placeholder icon

### ISSUE THREAD

**Issue by arshubham** [dhruv8sh/plasma6-window-title-applet#2]
Add Placeholder Icon along with placeholder text.

![image](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/14235191/01a23539-4a68-4bb5-96f2-37e0b61c6652)

**Comment by dhruv8sh** [comment]
Makes sense... I'll add it definitely as soon as I get time

**Comment by scgm0** [comment]
@arshubham #7 Try it?

**Comment by dhruv8sh** [comment]
Completed! Thanks to @scgm0.

**Comment by arshubham** [comment]
@scgm0 Thanks. Look perfect.
