### ISSUE TITLE
Centering

### ISSUE THREAD

**Issue by matiux** [dhruv8sh/plasma6-window-title-applet#21]
Is there a way to center the title?

![Screenshot_20240427_111806](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/821668/8024414a-da46-4852-bdaf-69375536ecf6)
![Screenshot_20240427_111834](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/821668/03a609bd-41d2-4131-9d65-42d407e7e0c1)

**Comment by dhruv8sh** [comment]
Not sure what you mean by that.
I don't understand what centering the title would do. Where would you center it if the entire widget is just that text (and an icon)?
Could be a little more descriptive?

**Comment by matiux** [comment]
My apologies, maybe I wasn't clear enough in my previous explanation. As you can se from my configuration above, I configured the applet to fill all available space. In this way, the applet covers the red area as in the image below. But the window title, "System settings", seems to be aligned to the left (green box). I would like to align to the center.
![Screenshot_20240427_112400](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/821668/57042c54-237c-48e1-9a9c-923b1bd86c82)

**Comment by schunka** [comment]
that could be acheived by adding space in panel on both sides of the title widget

**Comment by matiux** [comment]
@schunka thanks for your suggestion

**Comment by dhruv8sh** [comment]
So I finally have some time on my hands. I looked into the applet again and realised it has too much garbage code in it (not to disrespect psifidotos). There's a better way to handle all of this so that this becomes more customisable and ux friendly. I'll work on a complete rewrite of this, and ping you when it's completed.

**Comment by dhruv8sh** [comment]
Yea, so it's coming today.
