### ISSUE TITLE
Option to limit maximum width

### ISSUE THREAD

**Issue by Kishore96in** [dhruv8sh/plasma6-window-title-applet#24]
Currently, if the window title is too long, the applet becomes very wide and pushes other things off the panel. It would be good to have an option to set a maximum width for the applet (or even better, if it could automatically detect when the panel is full, and shorten the displayed text accordingly).

**Comment by dhruv8sh** [comment]
This already exists. Under the margins sections, set length style to "Maximum Length".
Note that text will not be elided if you are using multi-line text, issues are mentioned in the readme.

**Comment by BlueDrink9** [comment]
Is there a chance this behaviour could be modified to match https://github.com/psifidotos/applet-window-title
By default, it seems with maximum length set, the text would be truncated to less than maximum length if it would have run into the next panel. At least, my machine with https://github.com/psifidotos/applet-window-title does that, but my machine with this repo does not. The alternative is currently having to set a fixed custom maximum length which is less than the actual available space, and is less resilient to changes in other panel sections.
