### ISSUE TITLE
Small enhancement similar to "finder"

### ISSUE THREAD

**Issue by emmyvinte** [dhruv8sh/plasma6-window-title-applet#4]
Hi, I was thinking of a fix for a "visual problem". The text in the placeholder (name that stays on the screen without any app open) usually has two text customization options, being: normal, bold. 

My suggestion would be to be able to choose between the first word in bold (or have some kind of tag to mark it) to create more harmony with the desktop environment. That way, when there is no app open, those who like to customize the plasma theme similar to macOS, would have the same "finder" (when the application is open, only on the desktop).

Thanks in advance.

App, name app bold, "menu" normal:
![image](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/117837570/461f1c9c-d6e8-47dc-abf2-984516d8e2e8)

Desktop, all bold: 
![image](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/117837570/62056fa4-e47d-4414-a764-1a3b7ba2ea4f)
placeholder text: (Dolphin      File      Edit      View      Go      Tools      Settings      Help)

**Comment by dhruv8sh** [comment]
Maybe what you are looking for is the <b>Global Menu Applet</b>. It already exists and is pre-installed on your system.

Looks something like this...
![image](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/67322047/bba21e98-96de-46c5-8e75-410687192f8b)

The feature you are asking for makes no sense, I am closing this issue.

**Comment by emmyvinte** [comment]
I don't think I was clear enough, what I meant was that when you're only on the desktop, with no app open, both the global menu and the extension (that one) are left without text, in which case you can place a placeholder, but it puts all the text in bold (unlike, for example, when you have an app open, like Dolphin, where the app's name is in bold and its menu is in normal letters - I know it's another extension).

What I'm talking about is bringing an option to customise the text of this extension so that when on the desktop, with no app open, I can add a placeholder similar to the open dolphin, as in the screenshot you sent.

Thanks again.

Translated with DeepL.com (free version)

**Comment by emmyvinte** [comment]
I recorded this video (it's not on plasma 6, but the example is valid):

https://youtu.be/DW2KPPJz56Q

Sorry, I know it's a small detail. Unfortunately I can't take my eye off these little things

**Comment by dhruv8sh** [comment]
I do get what you mean, but this might come across as confusing to many people if added as an option.

Here is a cool workaround for you...
Use HTML tags!

Example:
```<b>dolphin<b> File Search Edit View```
