### ISSUE TITLE
[Suggestion] Allow substitution for both application name and window title

### ISSUE THREAD

**Issue by Lgmrszd** [dhruv8sh/plasma6-window-title-applet#5]
It would be nice if there was a way to set substitution for the entire label through templates.
For example, `%a` for application name and `%w` for window title. Then substitution template replaces the entire label, and not only application name.

**Comment by dhruv8sh** [comment]
That actually sounds nice. I will definitely look into this.

**Comment by dhruv8sh** [comment]
Question:
![image](https://github.com/dhruv8sh/plasma6-window-title-applet/assets/67322047/cdf8f4c7-7e18-40d1-9674-9e37c7b43d26)
Does this suffice?

You can substitute ".*" with something like "%w-%a", or do you think it would be better for me to add a "Custom" option with a textfield to the "Label Style" to make it more obvious. It would take some work, but only if you need it.

**Comment by dhruv8sh** [comment]
I will be closing this issue, comment if you want something else.
This update will be pushed now!
